# Generated by Django 5.2.7 on 2025-12-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bugs", "0002_alter_bugs_assignee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bugs",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("started", "Started"),
                    ("resolved", "Resolved"),
                    ("completed", "Completed"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="bugs",
            name="type",
            field=models.CharField(
                choices=[("bug", "Bug"), ("feature", "Feature")], max_length=30
            ),
        ),
    ]
