# Generated by Django 5.2.7 on 2026-01-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bugs", "0003_alter_bugs_status_alter_bugs_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bugs",
            name="bug_files",
        ),
        migrations.AddField(
            model_name="bugs",
            name="bug_attachment",
            field=models.ImageField(
                blank=True, null=True, upload_to="bug_attachments/"
            ),
        ),
    ]
